Sparse Matrix and its representations : 

Matrix : two-dimensional data object made of m rows and n columns.
 therefore having total m x n values. 
 
Sparse Matrix : If most of the elements of the matrix have 0 value, then it is called a sparse matrix.

We store only non-zero elements in a sparse matrix as a triplet(Row, column, value). 

Some common representations:
1. Array Representation
2. Linked List Representation
3. CSR Format

*Method 1 : Using Arrays*

2D array is used to represent a sparse matrix in which there are 3 rows :

        Row indexes
        Column indexes
        Non zero value

In [21]:
## Code to represent sparse matrix in array representation 
import numpy as np

# sparse_matrix = [[2,0,0,1], [0,0,3,4], [1,6,0,0], [0,0,0,8]]
sparse_matrix = [[0,0,3,0,4],[0,0,5,7,0],[0,0,0,0,0],[0,2,6,0,0]]

num_nnz = 0
for i, row in enumerate(sparse_matrix):
    for j, col in enumerate(row):
        if sparse_matrix[i][j]!=0:
            num_nnz +=1
            
print("Num of non zero elements {}".format(num_nnz))

output_array = np.zeros((3,num_nnz))
nnz =0
for i, row in enumerate(sparse_matrix):
    for j, col in enumerate(row):
        if sparse_matrix[i][j]!=0:
            output_array[0][nnz]=i
            output_array[1][nnz] = j
            output_array[2][nnz] = sparse_matrix[i][j]
            nnz +=1

print(output_array)

Num of non zero elements 6
[[0. 0. 1. 1. 3. 3.]
 [2. 4. 2. 3. 1. 2.]
 [3. 4. 5. 7. 2. 6.]]


##Using Linked List Representation for sparse matrices

In linked list, each node has four fields. These four fields are defined as: 

    Row: Index of row, where non-zero element is located
    Column: Index of column, where non-zero element is located
    Value: Value of the non zero element located at index – (row,column)
    Next node: Address of the next node


In [22]:
# Python Program for Representation of
# Sparse Matrix into Linked List

# Node Class to represent Linked List Node
class Node:

	# Making the slots for storing row,
	# column, value, and address
	__slots__ = "row", "col", "data", "next"

	# Constructor to initialize the values
	def __init__(self, row=0, col=0, data=0, next=None):

		self.row = row
		self.col = col
		self.data = data
		self.next = next


# Class to convert Sparse Matrix
# into Linked List
class Sparse:

	# Initialize Class Variables
	def __init__(self):
		self.head = None
		self.temp = None
		self.size = 0

	# Function which returns the size
	# of the Linked List
	def __len__(self):
		return self.size

	# Check the Linked List is
	# Empty or not
	def isempty(self):
		return self.size == 0

	# Responsible function to create
	# Linked List from Sparse Matrix
	def create_new_node(self, row, col, data):

		# Creating New Node
		newNode = Node(row, col, data, None)

		# Check whether the List is
		# empty or not
		if self.isempty():
			self.head = newNode
		else:
			self.temp.next = newNode
		self.temp = newNode

		# Incrementing the size
		self.size += 1

	# Function display the contents of
	# Linked List
	def PrintList(self):
		temp = r = s = self.head
		print("row_position:", end=" ")
		while temp != None:
			print(temp.row, end=" ")
			temp = temp.next
		print()
		print("column_postion:", end=" ")
		while r != None:
			print(r.col, end=" ")
			r = r.next
		print()
		print("Value:", end=" ")
		while s != None:
			print(s.data, end=" ")
			s = s.next
		print()

# Driver Code
if __name__ == "__main__":

	# Creating Object
	s = Sparse()

	# Assuming 4x5 Sparse Matrix
	sparseMatric = [[0, 0, 3, 0, 4],
					[0, 0, 5, 7, 0],
					[0, 0, 0, 0, 0],
					[0, 2, 6, 0, 0]]
	for i in range(4):
		for j in range(5):

			# Creating Linked List by only those
			# elements which are non-zero
			if sparseMatric[i][j] != 0:
				s.create_new_node(i, j, sparseMatric[i][j])

	# Printing the Linked List Representation
	# of the sparse matrix
	s.PrintList()

	# This code is contributed by Naveen Rathore


row_position: 0 0 1 1 3 3 
column_postion: 2 4 2 3 1 2 
Value: 3 4 5 7 2 6 


    ##CSR Format is a very commonly used format for sparse matrix representation. 

    CSR Format - Compressed Sparse Row Format. 

    ##Algorithm for converting Sparse matrix to CSR Format

    SPARSIFY (MATRIX)

    Step 1: Set M to number of rows in MATRIX

    Step 2: Set N to number of columns in MATRIX

    Step 3: I = 0, NNZ = 0. Declare A, JA, and IA. 
            Set IA[0] to 0

    Step 4: for I = 0 ... N-1

    Step 5: for J = 0 ... N-1

    Step 6: If MATRIX [I][J] is not zero

               Add MATRIX[I][J] to A

               Add J to JA

               NNZ = NNZ + 1

            [End of IF]

    Step 7: [ End of J loop ]

            Add NNZ to IA

            [ End of I loop ]

    Step 8: Print vectors A, IA, JA

    Step 9: END

The sparsity of the matrix A(m*n) = (1 – NNZ/mn ) or ( 1 – size(A)/mn ) .

The direct array based representation required memory 3 * NNZ wile CSR requires ( 2*NNZ + m + 1) memory.

CSR matrices are memory efficient as long as NNZ < (m*(n-1) - 1)/2 .

In [23]:
sparse_matrix = [[0, 0, 3, 0, 4],
                 [0, 0, 5, 7, 0],
                 [0, 0, 0, 0, 0],
                 [0, 2, 6, 0, 0]]
                
sparse_matrix

[[0, 0, 3, 0, 4], [0, 0, 5, 7, 0], [0, 0, 0, 0, 0], [0, 2, 6, 0, 0]]

In [24]:
A = []  #Stores the nnz values
IA = [0]  
JA = []  #Stores the column values for each nnz

row_count = 0
for i,row in enumerate(sparse_matrix):
    for j, col in enumerate(row):
        if sparse_matrix[i][j]!=0:
            A.append(sparse_matrix[i][j])
            JA.append(j)
            row_count += 1
    IA.append(row_count)

print("A {}".format(A))
print("JA {}".format(JA))
print("IA {}".format(IA))

A [3, 4, 5, 7, 2, 6]
JA [2, 4, 2, 3, 1, 2]
IA [0, 2, 4, 4, 6]
