Sparse Matrix and its representations : 

Matrix : two-dimensional data object made of m rows and n columns.
 therefore having total m x n values. 
 
Sparse Matrix : If most of the elements of the matrix have 0 value, then it is called a sparse matrix.

We store only non-zero elements in a sparse matrix as a triplet(Row, column, value). 

Some common representations:
1. Array Representation
2. Linked List Representation

*Method 1 : Using Arrays*

2D array is used to represent a sparse matrix in which there are 3 rows :
1. Row indexes
2. Column indexes
3. Non zero value

In [11]:
## Code to represent sparse matrix in array representation 
import numpy as np

# sparse_matrix = [[2,0,0,1], [0,0,3,4], [1,6,0,0], [0,0,0,8]]
sparse_matrix = [[0,0,3,0,4],[0,0,5,7,0],[0,0,0,0,0],[0,2,6,0,0]]

num_nnz = 0
for i, row in enumerate(sparse_matrix):
    for j, col in enumerate(row):
        if sparse_matrix[i][j]!=0:
            num_nnz +=1
            
print("Num of non zero elements {}".format(num_nnz))

output_array = np.zeros((3,num_nnz))
nnz =0
for i, row in enumerate(sparse_matrix):
    for j, col in enumerate(row):
        if sparse_matrix[i][j]!=0:
            output_array[0][nnz]=i
            output_array[1][nnz] = j
            output_array[2][nnz] = sparse_matrix[i][j]
            nnz +=1

print(output_array)

Num of non zero elements 6
[[0. 0. 1. 1. 3. 3.]
 [2. 4. 2. 3. 1. 2.]
 [3. 4. 5. 7. 2. 6.]]
